# Generated by Django 5.2.1 on 2025-05-26 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noteapp', '0002_note_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='user',
        ),
    ]
